base_model: TinyLlama/TinyLlama-1.1B-intermediate-step-1431k-3T
model_type: LlamaForCausalLM
tokenizer_type: LlamaTokenizer
is_llama_derived_model: true

load_in_8bit: false
load_in_4bit: false
strict: false

datasets:
  - path: Emm9625/sum0214
    # data_files: articles_train.jsonl
    type: sharegpt
    conversation: chatml
chat_template: chatml
default_system_message: ""
dataset_prepared_path: /workspace/last_run_prepared
val_set_size: 0
output_dir: ./lora-out

sequence_len: 4096
sample_packing: true
pad_to_sequence_len: true

hf_use_auth_token: true # boolean
# push checkpoints to hub
# repo path to push finetuned model
hub_model_id: Emm9625/TL-sum0215-r01-test
hub_strategy: checkpoint

wandb_project: TL-L-sum0215
wandb_entity:
wandb_watch:
wandb_name: testing
wandb_log_model:

gradient_accumulation_steps: 4
micro_batch_size: 2
num_epochs: 3
optimizer: paged_adamw_8bit
lr_scheduler: cosine
learning_rate: 0.0002

train_on_inputs: false
group_by_length: false
bf16: auto
fp16:
tf32: false

gradient_checkpointing: true
early_stopping_patience:
resume_from_checkpoint:
local_rank:
logging_steps: 1
xformers_attention:
flash_attention: true
flash_attn_cross_entropy: false
flash_attn_rms_norm: true
flash_attn_fuse_qkv: false
flash_attn_fuse_mlp: true
warmup_ratio: 0.025
evals_per_epoch: 0
saves_per_epoch: 25
debug:
deepspeed:
weight_decay: 0.0
fsdp:
fsdp_config: